services:
  db:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: sajang
        MYSQL_USER: sajang
        MYSQL_PASSWORD: sajangpass
      ports:
        - "3306:3306"
      volumes:
        - ../mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./secure/.env
    volumes:
      - .:/app
      - ./secure:/secure:ro
      - ./nadostatic/silk:/var/www/silk
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 6
      --threads 2
      --timeout 60
      --access-logfile '-' 
      --error-logfile '-'



