services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./secure/.env
    volumes:
      - .:/app
      - ./secure:/secure:ro
      - ./silk:/var/www/silk
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sajang
      MYSQL_USER: sajang
      MYSQL_PASSWORD: sajangpass
    ports:
      - "3306:3306"
    volumes:
      - ../mysql-data:/var/lib/mysql


